name: dart_license_plist
version: 1.0.1

description: command-line tool to generate a license plist file for the Dart programming language.
repository: https://github.com/nomunomu0504/dart_license_plist

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  collection: ^1.16.0
  path: ^1.8.0
  yaml: ^3.1.0
  html: ^0.15.0
  http: ^0.13.4
  interact: ^2.1.1
  pub_updater: ^0.2.2
  xml: ^5.3.1

dev_dependencies:
  lints: ^1.0.0

platforms:
  ios:
  macos:
